#!/usr/bin/env php
<?php

use Dais\PlatformShFacade;
use Dais\WaitCommand;

require __DIR__ . '/vendor/autoload.php';


$app = new Silly\Edition\PhpDi\Application('Dais', '@git-version@');

$app->command('wait [files]*', 'Dais\\WaitCommand');
$app->setDefaultCommand('wait', true);

$app->run();
