#!/usr/bin/env php
<?php

use Dais\PlatformShFacade;
use Dais\WaitCommand;

require __DIR__ . '/vendor/autoload.php';


$app = new Silly\Application();

$app->command('wait file', new WaitCommand());
$app->setDefaultCommand('wait', true);

$app->run();
